### PR TITLE
Use cURL instead of file_get_contets for https API calls

### PR DESCRIPTION
**Pull request by joeyrush**

### CODE REVIEW

**Comment by mattsah** [comment]
For the record, it is completely possible to disable peer verification using stream context:

```php
stream_context_create([
	'http' => [
		/* HTTP options */ 
	],
	'ssl' => [
		'verify_peer'      => FALSE,
		'verify_peer_name' => FALSE,
    ]
]);
```

This could still be used with file_get_contents while simultaneously not requiring curl as a module dependency.

**Comment by khamer** [comment]
Yes, @joeyrush can you provide any description about why you're switching to using cURL? It might be nice to at least wrap this functionality and check if the curl module is provided and fallback to `file_get_contents` if it isn't.

**Comment by joeyrush** [comment]
@mattsah, @khamer  I think that this may be the reason why file_get_contents wasn't working for me http://stackoverflow.com/a/9659169/5818271 but I couldn't say for sure. This was a rushed solution which worked for what I was working with without doing too much research

**Comment by mattsah** [comment]
@joeyrush 

So your fix is better, but my concern is still why google's SSL would need peer verification disabled.  This is usually only required with bad or self-signed certificates.  Are you able to test with CURL but removing the line which does this?

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);`

If that works, I'd be inclined to remove the verify peer flags but accept curl as an option for those who disable URL opens.  But there shouldn't be a need to disable peer verification.

**Pull request merged**
